<?php

require_once __DIR__ . "/config.php";
////////BENCHAMIN LOUIS//////
//CHANNEL:- T.ME/INDUSBOTS////
error_reporting(0);

set_time_limit(0);

flush();
##------------------------------##
define('API_KEY',$BOT_TOKEN);

ini_set("log_errors","off");
function Bot($method,$datas=[]){
$url = "https://api.telegram.org/bot".API_KEY."/".$method;
$ch = curl_init();
curl_setopt($ch,CURLOPT_URL,$url);
curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
curl_setopt($ch,CURLOPT_POSTFIELDS,$datas);
$res = curl_exec($ch);
if(curl_error($ch)){
var_dump(curl_error($ch));
}else{
return json_decode($res);
}
}
$update = json_decode(file_get_contents('php://input'));
$message = $update->message;
$chat_id = $message->chat->id;
$message_id = $message->message_id;
$from_id = $message->from->id;
$first_name = $message->from->first_name;
$last_name = $message->from->last_name;
$username = $message->from->username;
$msg = $message->text;

if($msg == '/start'){
Bot('sendmessage',[
'chat_id'=>$chat_id,
'text'=> "***Hello 👋 $first_name,

I'm a Random Data Generator Bot. I can Generate Random Data Of Usa Citizens

Type /gen To Generate Random Datas***",
'parse_mode'=>"MarkDown",

]);

}else{
$get = json_decode(file_get_contents('https://api.unsplash.com/photos/random/?client_id=iQusL6U8pY8Ln3EgVlfosLzqbZnjaT0GiI0V9eiJWi4'),true);

$id = $get['id'];
$created =  $get['created_at'];
$width =  $get['width'];
$height = $get['height'];
$colour = $get['colour'];
$description = $get['of'][0]['alt_description'];
$photo = $get['urls'][0]['regular'];

if($msg == '/gen')
Bot('sendphoto',[
'chat_id'=>$chat_id,
'photo'=>$photo
'caption'=> "***🌐 Generated Data 🌐***

***FIRST NAME***: `$created`

***GENDER*** : `$width`

***STREET*** : `$height`

***CITY*** : `$colour`

***STATE*** : `$description`

***GENERATED BY*** : @$username


***GENERATED FROM:- $username***",
'parse_mode'=>"MarkDown",
]);
}
